site_name: Map of zones Docs
nav:
    - Getting started: index.md
    - Architecture: architecture.md
    - Front: front.md
    - GraphQL: graphql.md
    - GraphQL public schema Types: data/schema.md
    - GraphQL admin schema Types: data/schema2.md
    - Database: database.md
    - Stats adaptor: adaptor.md
    - Tx processor: processor.md
    - Message broker: broker.md
    - Watcher: watcher.md
    - Proxy: proxy.md
    - CI/CD/CD: ci&cd&cd.md
    - Changelog: changelog.md
theme: readthedocs
plugins:
  - diagrams
  - search
