# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Setup Graphviz
        # You may pin to the exact commit or the version.
        # uses: ts-graphviz/setup-graphviz@f1590cf4e989dd1429bff4fd6339e098050a1657
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install mkdocs diagrams
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-diagrams

      - name: Mkdocs build
        run: mkdocs build
              
      - name: Pushes to gh-pages branch
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './site'
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: ${{ github.event.repository.name }}
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          target-branch: gh-pages
      - name: Notify Telegram
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.chat }} # user id or channel name secret
          token: ${{ secrets.token }} # token secret
          status: ${{ job.status }} # do not modify this line
