# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Install mkdocs diagrams
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-diagrams

#       - name: Install graphviz
#         run: sudo apt install graphviz
        
      - name: Setup Graphviz
        # You may pin to the exact commit or the version.
        # uses: ts-graphviz/setup-graphviz@f1590cf4e989dd1429bff4fd6339e098050a1657
        uses: ts-graphviz/setup-graphviz@v1
        
      - name: MkDocs Simple action
        # You may pin to the exact commit or the version.
        # uses: athackst/mkdocs-simple-plugin@d02154f9e00f61d3c87721b5bb9ebb7ae22a800a
        uses: athackst/mkdocs-simple-plugin@v0.2.1
#         with:
          # Set a target branch for deployment.
#           publish_branch: # optional, default is gh-pages
          # Set the repository url.
#           repo_url: # optional, default is https://github.com/${{ github.repository }}
          # Set the site name.
#           site_name: # optional, default is ${{ github.repository }}
          # Set the site url.
#           site_url: # optional, default is https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
